GET http://127.0.0.1:8000/

###
GET http://127.0.0.1:8000/api/v1/agendamentos/

###
POST http://127.0.0.1:8000/api/v1/agendamentos/  HTTP/1.1
content-type: application/json

{
    "data_agendamento" : "12/12/2020 08:00",
    "user_id" : "50507737334",
}

###
GET http://127.0.0.1:8000/api/v1/agendamentos/sdgdgfgdg
