GET http://127.0.0.1:8000/

###
GET http://127.0.0.1:8000/api/v1/agendamentos/

###
POST http://127.0.0.1:8000/api/v1/agendamentos/  HTTP/1.1
content-type: application/json

{
    "user_id" : "50507737334",
    "data_agendametno" : "12/12/2020 08:00",
    "vacina_id" : "feafe51feesss",
    "co_unidade" : "21555225",
    "senha" : "testesenha"
}

###
GET http://127.0.0.1:8000/api/v1/agendamentos/fee12feggeeefeee
