# Generated by Django 3.1.4 on 2020-12-18 02:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id_vacina', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=15)),
                ('doses', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LoteVacina',
            fields=[
                ('id_lote_vacina', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=255)),
                ('data_validade', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('quantidade_estoque', models.IntegerField()),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacinacao.vacina')),
            ],
        ),
    ]
