# Generated by Django 3.1.4 on 2020-12-20 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacinacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='nome',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='salario',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
