# Generated by Django 3.1.4 on 2020-12-20 14:30
from django.contrib.auth.management import create_permissions
from django.db import migrations
from django.contrib.auth.models import Group, User
from django.contrib.auth.models import Permission
from django.core.management.sql import emit_post_migrate_signal
from django.conf import settings
from vacinacao.models import Vacina, Agenda

def criar_grupos(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    emit_post_migrate_signal(2, False, db_alias)
    # criar grupos automaticamente
    Group.objects.create(name=settings.GRUPOS['profissional'])
    groupProfissional = Group.objects.get(name=settings.GRUPOS['profissional'])
    codenames = ['change_vacinacao', 'view_vacinacao',
    'add_lotevacina', 'change_lotevacina', 'delete_lotevacina', 'view_lotevacina',
    'view_vacina', 'view_paciente', 'view_estabelecimento', 'view_agenda',
    'aplicar_vacina', 'aprovar_vacina']
    permissoes = Permission.objects.filter(codename__in=codenames)
    groupProfissional.permissions.add(*permissoes)
    groupProfissional.save()

    Group.objects.create(name=settings.GRUPOS['coordenador'])
    groupCoordenador = Group.objects.get(name=settings.GRUPOS['coordenador'])
    codenames = ['add_municipio', 'change_municipio', 'delete_municipio', 'view_municipio',
    'add_estabelecimento', 'change_estabelecimento', 'delete_estabelecimento', 'view_estabelecimento',
    'add_vacina', 'change_vacina', 'delete_vacina', 'view_vacina',
    'add_profissional', 'change_profissional', 'delete_profissional', 'view_profissional',
    'add_vinculoprofissional', 'change_vinculoprofissional', 'delete_vinculoprofissional', 'view_vinculoprofissional',
    'add_agenda', 'change_agenda', 'delete_agenda', 'view_agenda',
    'view_lotevacina', 'view_paciente', 'view_vacinacao']
    permissoes = Permission.objects.filter(codename__in=codenames)
    groupCoordenador.permissions.add(*permissoes)
    groupCoordenador.save()

    Group.objects.create(name=settings.GRUPOS['paciente'])
    groupPaciente = Group.objects.get(name=settings.GRUPOS['paciente'])
    codenames = ['add_vacinacao', 'view_agenda']
    permissoes = Permission.objects.filter(codename__in=codenames)
    groupPaciente.permissions.add(*permissoes)
    groupPaciente.save()

def popular_vacina(apps, schema_editor):
    Vacina.objects.create(descricao='vacina contra a tuberculose', sigla='BCG')
    Vacina.objects.create(descricao='vacina contra a hepatite B', sigla='VHB')
    Vacina.objects.create(descricao='vacina contra a poliomielite', sigla='SABIN')
    Vacina.objects.create(descricao='vacina contra febre amarela', sigla='FA')
    Vacina.objects.create(descricao='vacina contra sarampo, caxumba e rubéola', sigla='Tríplice Viral')
"""
def popular_agenda(apps, schema_editor):
    Agenda.objects.create(data_agendamento='2020-12-22', hora='12', vacina=Vacina.objects.get(sigla='BSG'))
    Agenda.objects.create(data_agendamento='2020-12-22', hora='13', vacina=Vacina.objects.get(sigla='VHB'))
    Agenda.objects.create(data_agendamento='2020-12-22', hora='14', vacina=Vacina.objects.get(sigla='SABIN'))
    Agenda.objects.create(data_agendamento='2020-12-22', hora='15', vacina=Vacina.objects.get(sigla='FA'))
    Agenda.objects.create(data_agendamento='2020-12-22', hora='16', vacina=Vacina.objects.get(sigla='Tríplice Viral'))
"""
class Migration(migrations.Migration):
    dependencies = [
        ('vacinacao', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(criar_grupos),
        migrations.RunPython(popular_vacina),
        #migrations.RunPython(popular_agenda),
    ]