# Generated by Django 3.1.4 on 2020-12-18 17:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vacinacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotevacina',
            old_name='id_lote_vacina',
            new_name='lote_vacina_id',
        ),
        migrations.RenameField(
            model_name='vacina',
            old_name='id_vacina',
            new_name='vacina_id',
        ),
        migrations.CreateModel(
            name='Vacinacao',
            fields=[
                ('vacinacao_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_vacinacao', models.DateField()),
                ('data_aprovado', models.DateField()),
                ('data_agendamento', models.DateField()),
                ('data_solicitacao', models.DateField()),
                ('privada', models.BooleanField()),
                ('vacinado', models.BooleanField()),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacinacao.vacina')),
            ],
        ),
    ]
