# Generated by Django 3.1.4 on 2020-12-20 14:30
from django.contrib.auth.management import create_permissions
from django.db import migrations
from django.contrib.auth.models import Group, User
from django.contrib.auth.models import Permission
from django.core.management.sql import emit_post_migrate_signal
from django.conf import settings

def criar_grupos(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    emit_post_migrate_signal(2, False, db_alias)
    # criar grupos automaticamente
    Group.objects.create(name=settings.GRUPOS['profissional'])
    groupProfissional = Group.objects.get(name=settings.GRUPOS['profissional'])
    codenames = ['add_vacinacao', 'change_vacinacao', 'delete_vacinacao', 'view_vacinacao',
    'add_lotevacina', 'change_lotevacina', 'delete_lotevacina', 'view_lotevacina',
    'view_vacina', 'view_paciente', 'view_estabelecimento'
    'aplicar_vacina', 'aprovar_vacina']
    permissoes = Permission.objects.filter(codename__in=codenames)
    groupProfissional.permissions.add(*permissoes)
    groupProfissional.save()

    Group.objects.create(name=settings.GRUPOS['coordenador'])
    groupCoordenador = Group.objects.get(name=settings.GRUPOS['coordenador'])
    codenames = ['add_municipio', 'change_municipio', 'delete_municipio', 'view_municipio',
    'add_estabelecimento', 'change_estabelecimento', 'delete_estabelecimento', 'view_estabelecimento',
    'add_vacina', 'change_vacina', 'delete_vacina', 'view_vacina'
    'add_profissional', 'change_profissional', 'delete_profissional', 'view_profissional',
    'add_vinculoprofissional', 'change_vinculoprofissional', 'delete_vinculoprofissional', 'view_vinculoprofissional',
    'view_lotevacina', 'view_paciente', 'view_vacinacao']
    permissoes = Permission.objects.filter(codename__in=codenames)
    groupCoordenador.permissions.add(*permissoes)
    groupCoordenador.save()

    Group.objects.create(name=settings.GRUPOS['paciente'])
    groupPaciente = Group.objects.get(name=settings.GRUPOS['paciente'])
    codenames = ['']
    permissoes = Permission.objects.filter(codename__in=codenames)
    groupPaciente.permissions.add(*permissoes)
    groupPaciente.save()

class Migration(migrations.Migration):
    dependencies = [
        ('vacinacao', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(criar_grupos),
    ]
