# Generated by Django 3.1.4 on 2020-12-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinacao', '0002_baseGroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='bairro',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_nascimento',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='endereco',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
