# Generated by Django 3.1.4 on 2020-12-20 14:30
from django.contrib.auth.management import create_permissions
from django.db import migrations
from django.contrib.auth.models import Group, User
from django.contrib.auth.models import Permission
from django.core.management.sql import emit_post_migrate_signal
from django.conf import settings

def criar_grupos(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    emit_post_migrate_signal(2, False, db_alias)
    # criar grupos automaticamente
    Group.objects.create(name=settings.GRUPOS['profissional'])
    groupProfissional = Group.objects.get(name=settings.GRUPOS['profissional'])
    codenames = ['aplicar_vacina', 'aprovar_vacina']
    permissoes = Permission.objects.filter(codename__in=codenames)
    groupProfissional.permissions.add(*permissoes)
    groupProfissional.save()

    grupoCoordenador = Group.objects.create(name=settings.GRUPOS['coordenador'])
    grupoPaciente = Group.objects.create(name=settings.GRUPOS['paciente'])

class Migration(migrations.Migration):
    dependencies = [
        ('vacinacao', '0002_auto_20201220_1057'),
    ]
    operations = [
        migrations.RunPython(criar_grupos),
    ]
