# Generated by Django 3.1.4 on 2020-12-20 14:30

from django.db import migrations
from django.contrib.auth.models import Group, User
from django.contrib.auth.models import Permission
from django.conf import settings

def criar_grupos(apps, schema_editor):
    # criar grupos automaticamente
    Group.objects.create(name=settings.GRUPOS["profissional"])
    groupProfissional = Group.objects.get(name=settings.GRUPOS["profissional"])
    grupoCoordenador = Group.objects.create(name=settings.GRUPOS["coordenador"])
    grupoPaciente = Group.objects.create(name=settings.GRUPOS["paciente"])

class Migration(migrations.Migration):

    dependencies = [
        ('vacinacao', '0002_auto_20201220_1057'),
    ]

    operations = [
        migrations.RunPython(criar_grupos),
    ]
