# Generated by Django 3.1.4 on 2020-12-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinacao', '0003_auto_20201218_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.IntegerField()),
                ('nome_uf', models.CharField(max_length=20)),
                ('codigo_municipio', models.IntegerField()),
                ('nome_municipio', models.CharField(max_length=100)),
            ],
        ),
    ]
