# Generated by Django 3.1.4 on 2020-12-19 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacinacao', '0004_municipio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacinacao',
            name='user_id',
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('paciente_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, verbose_name='número do cpf')),
                ('data_validade', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vacinacao',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vacinacao.paciente'),
        ),
    ]
